<?php
require_once __DIR__.'/../delivery_common.php';$uid=dc_uid();if(!$uid)die('Login required');
$orderId=(int)($_GET['order_id']??0);
$q=$pdo->prepare("SELECT o.*,u.name customer_name,u.phone customer_phone FROM shop_orders o JOIN users u ON u.id=o.customer_user_id WHERE o.id=? AND o.assigned_staff_id=?");$q->execute([$orderId,$uid]);$o=$q->fetch();if(!$o)die('This delivery is not assigned to you.');
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(isset($_POST['message'])&&trim($_POST['message'])!=='')$pdo->prepare("INSERT INTO delivery_chat_messages(order_id,sender_user_id,message) VALUES(?,?,?)")->execute([$orderId,$uid,trim($_POST['message'])]);
 if(isset($_POST['offer_product'])){$pid=(int)$_POST['offer_product'];$p=$pdo->prepare("SELECT price,stock_qty FROM shop_products WHERE id=? AND status='active'");$p->execute([$pid]);$p=$p->fetch();$qty=max(.01,(float)$_POST['offer_qty']);if($p&&$p['stock_qty']>=$qty)$pdo->prepare("INSERT INTO delivery_product_offers(order_id,delivery_user_id,customer_user_id,product_id,qty,unit_price) VALUES(?,?,?,?,?,?)")->execute([$orderId,$uid,$o['customer_user_id'],$pid,$qty,$p['price']]);}
 if(isset($_POST['collect_payment'])){$amount=(float)$_POST['collected_amount'];$pdo->prepare("INSERT INTO delivery_collections(order_id,delivery_user_id,bill_amount,collected_amount,payment_method,reference_no) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE collected_amount=VALUES(collected_amount),payment_method=VALUES(payment_method),reference_no=VALUES(reference_no),collected_at=NOW()")->execute([$orderId,$uid,(float)$o['total_amount'],$amount,$_POST['pay_method'],trim($_POST['pay_ref']??'')]);}
 header("Location: delivery_commerce.php?order_id=".$orderId);exit;
}
$m=$pdo->prepare("SELECT m.*,u.name sender_name FROM delivery_chat_messages m JOIN users u ON u.id=m.sender_user_id WHERE order_id=? ORDER BY m.id");$m->execute([$orderId]);$msgs=$m->fetchAll();
$products=$pdo->query("SELECT id,name,price,stock_qty,unit FROM shop_products WHERE status='active' AND stock_qty>0 ORDER BY name")->fetchAll();
$col=$pdo->prepare("SELECT * FROM delivery_collections WHERE order_id=?");$col->execute([$orderId]);$col=$col->fetch();
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Delivery Console</title><style>body{font-family:Segoe UI;background:#f3f7f5;color:#17372b}.w{max-width:900px;margin:auto;padding:22px}.c{background:#fff;padding:18px;border-radius:15px;margin:12px 0;border:1px solid #dde9e2}.chat{height:260px;overflow:auto;background:#f7faf8;padding:10px}.m{background:white;padding:8px;margin:6px;border-radius:8px}.row{display:flex;gap:8px;flex-wrap:wrap}input,select,button{padding:10px;border:1px solid #cad8d0;border-radius:8px}button{background:#176b4b;color:#fff;border:0}.money{font-size:30px;font-weight:800}</style></head><body><div class="w"><a href="<?=htmlspecialchars(dc_back())?>">← Back</a><div class="c"><h2>Delivery #<?=$orderId?></h2><b><?=htmlspecialchars($o['customer_name'])?></b> · <?=htmlspecialchars($o['customer_phone'])?><p>Bill is revealed at handover/payment stage.</p></div><div class="c"><h3>Customer chat</h3><div class="chat"><?php foreach($msgs as $x):?><div class="m"><b><?=htmlspecialchars($x['sender_name'])?>:</b> <?=htmlspecialchars($x['message'])?></div><?php endforeach;?></div><form method="post" class="row"><input style="flex:1" name="message" required placeholder="Reply to customer"><button>Send</button></form></div><div class="c"><h3>Offer another available product</h3><form method="post" class="row"><select name="offer_product"><?php foreach($products as $p):?><option value="<?=$p['id']?>"><?=htmlspecialchars($p['name'])?> · ৳<?=$p['price']?> · stock <?=$p['stock_qty']?> <?=$p['unit']?></option><?php endforeach;?></select><input type="number" step=".01" min=".01" name="offer_qty" value="1"><button>Send Offer</button></form><small>Use this after the customer asks about another product. Customer must accept the offer.</small></div><div class="c"><h3>Handover & payment</h3><div class="money">Due: ৳<?=number_format((float)$o['total_amount'],2)?></div><?php if($col):?><p>Collected ৳<?=number_format($col['collected_amount'],2)?> via <?=htmlspecialchars($col['payment_method'])?> · <?=$col['handover_status']?></p><?php else:?><form method="post" class="row"><input type="hidden" name="collect_payment" value="1"><input type="number" step=".01" name="collected_amount" value="<?=htmlspecialchars($o['total_amount'])?>" required><select name="pay_method"><option value="cash">Cash on delivery</option><option value="bkash">bKash</option><option value="nagad">Nagad</option><option value="other_mfs">Other MFS</option></select><input name="pay_ref" placeholder="MFS transaction ID"><button>Accept Payment</button></form><?php endif;?></div><div class="c"><a href="settlement.php">Daily collection & company settlement →</a></div></div></body></html>